packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - bcrypt

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - sharp
