/**
 * Options for profile dropdowns (nationality, country of study, academic year).
 * Kept in sync with scholar app where applicable.
 */

export const GENDER_OPTIONS = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'other', label: 'Other' },
  { value: 'prefer_not_to_say', label: 'Prefer not to say' },
] as const;

export const ACADEMIC_YEAR_OPTIONS = [
  'Pre-University',
  'Foundation',
  'Year 1',
  'Year 2',
  'Year 3',
  'Year 4',
  'Year 5',
  'Postgraduate',
] as const;

/** All countries (ISO-style names, A–Z) for nationality and country of study dropdowns. */
export const COUNTRY_OPTIONS: readonly string[] = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Other',
];

/**
 * Map common demonyms (e.g. "Mauritian") to country names (e.g. "Mauritius")
 * so we store and display country names consistently.
 */
export const DEMONYM_TO_COUNTRY: Record<string, string> = {
  American: 'United States',
  Australian: 'Australia',
  Austrian: 'Austria',
  Bangladeshi: 'Bangladesh',
  Belgian: 'Belgium',
  Brazilian: 'Brazil',
  British: 'United Kingdom',
  Canadian: 'Canada',
  Chinese: 'China',
  Colombian: 'Colombia',
  Dutch: 'Netherlands',
  Egyptian: 'Egypt',
  English: 'United Kingdom',
  Ethiopian: 'Ethiopia',
  Filipino: 'Philippines',
  Finnish: 'Finland',
  French: 'France',
  German: 'Germany',
  Ghanaian: 'Ghana',
  Greek: 'Greece',
  Indian: 'India',
  Indonesian: 'Indonesia',
  Irish: 'Ireland',
  Israeli: 'Israel',
  Italian: 'Italy',
  Japanese: 'Japan',
  Kenyan: 'Kenya',
  Korean: 'South Korea',
  Lebanese: 'Lebanon',
  Malaysian: 'Malaysia',
  Mauritian: 'Mauritius',
  Mexican: 'Mexico',
  Moroccan: 'Morocco',
  Nepalese: 'Nepal',
  Nigerian: 'Nigeria',
  Norwegian: 'Norway',
  Pakistani: 'Pakistan',
  Palestinian: 'Palestine',
  Peruvian: 'Peru',
  Polish: 'Poland',
  Portuguese: 'Portugal',
  Russian: 'Russia',
  Saudi: 'Saudi Arabia',
  Scottish: 'United Kingdom',
  Singaporean: 'Singapore',
  'South African': 'South Africa',
  Spanish: 'Spain',
  'Sri Lankan': 'Sri Lanka',
  Swedish: 'Sweden',
  Swiss: 'Switzerland',
  Thai: 'Thailand',
  Tunisian: 'Tunisia',
  Turkish: 'Turkey',
  Ugandan: 'Uganda',
  Ukrainian: 'Ukraine',
  Vietnamese: 'Vietnam',
  Welsh: 'United Kingdom',
  Zambian: 'Zambia',
  Zimbabwean: 'Zimbabwe',
};

/**
 * Normalize nationality to a country name (demonym → country).
 * Returns the country name for display and storage.
 */
export function normalizeNationality(raw: string | undefined): string {
  const trimmed = raw?.trim() ?? '';
  if (!trimmed) return '';
  return DEMONYM_TO_COUNTRY[trimmed] ?? trimmed;
}

/**
 * Normalize location to a country-only value. If the stored value is a full address,
 * try to detect a country name from it; otherwise return empty so user picks from dropdown.
 */
export function normalizeLocation(
  raw: string | undefined,
  countryOptions: readonly string[] = COUNTRY_OPTIONS
): string {
  const trimmed = raw?.trim() ?? '';
  if (!trimmed) return '';
  if (countryOptions.includes(trimmed)) return trimmed;
  // Looks like an address: try to find a country in it (e.g. last part after comma, or substring)
  const parts = trimmed.split(/[,;]/).map((p) => p.trim()).filter(Boolean);
  for (let i = parts.length - 1; i >= 0; i--) {
    const part = parts[i];
    if (part && countryOptions.includes(part)) return part;
  }
  for (const country of countryOptions) {
    if (country === 'Other' || !country) continue;
    if (trimmed.includes(country)) return country;
  }
  return '';
}

/** University options used when API filter options are empty (e.g. scholar app list). */
export const DEFAULT_UNIVERSITY_OPTIONS = [
  'Imperial College London',
  'University of Edinburgh',
  'LSE',
  'Cambridge University',
  'Oxford University',
  'UCL',
  'University of York',
  'University of Warwick',
  'University of Central Lancashire',
  'University of East Anglia',
  'University of Manchester',
  'University of Leeds',
] as const;
