import {
  buildPendingResourceFileKey,
  buildPermanentResourceFileKey,
  isPendingResourceFileKey,
  sanitizeResourceFileName,
} from './resource-files';

describe('resource file keys', () => {
  it('sanitizes file names', () => {
    expect(sanitizeResourceFileName('Scholar Handbook (2026).pdf')).toBe(
      'Scholar_Handbook_2026_.pdf'
    );
  });

  it('builds pending keys under the pending prefix', () => {
    expect(buildPendingResourceFileKey('upload-1', 'Guide.pdf')).toBe(
      'resources/pending/upload-1-Guide.pdf'
    );
  });

  it('builds permanent keys under the resource id', () => {
    expect(buildPermanentResourceFileKey('resource-1', 'Guide.pdf', 1700000000000)).toBe(
      'resources/resource-1/1700000000000-Guide.pdf'
    );
  });

  it('accepts only pending keys generated by the API', () => {
    expect(isPendingResourceFileKey('resources/pending/abc-Guide.pdf')).toBe(true);
    expect(isPendingResourceFileKey('resources/resource-1/abc-Guide.pdf')).toBe(false);
    expect(isPendingResourceFileKey('resources/pending/../secret.pdf')).toBe(false);
    expect(isPendingResourceFileKey('resources/pending/nested/path.pdf')).toBe(false);
  });
});
